spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.flyway.schemas=catalog

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.security.user.name=catalog_service_user
spring.security.user.password=password
spring.security.user.roles=SERVICE

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8888/realms/selmag

spring.security.oauth2.client.registration.keycloak.client-id=catalog-service-metrics-client
spring.security.oauth2.client.registration.keycloak.client-secret=oYKPkAQUdJe1VkNq3L3ptIDu0Ian8pvo
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=client_credentials
spring.security.oauth2.client.registration.keycloak.scope=metrics_server
spring.security.oauth2.client.provider.keycloak.issuer-uri=http://localhost:8888/realms/selmag

spring.boot.admin.client.enabled=false
spring.boot.admin.client.url=http://localhost:8085
spring.boot.admin.client.instance.name=catalog-service
spring.boot.admin.client.instance.service-host-type=ip

management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true
management.endpoints.web.exposure.include=*

management.tracing.enabled=false
management.tracing.sampling.probability=1.0
management.opentelemetry.tracing.export.otlp.endpoint=http://localhost:4318/v1/traces
management.opentelemetry.logging.export.otlp.endpoint=http://localhost:4318/v1/logs
management.otlp.metrics.export.url=http://localhost:4318/v1/metrics

#spring.zipkin.base-url=http://192.168.31.111:9411/
#management.tracing.sampling.probability=1.0
#management.zipkin.tracing.endpoint=http://192.168.31.111:9411/api/v2/spans
eureka.client.enabled=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true
